# Generated by Django 4.2.1 on 2024-01-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_2',
            field=models.ImageField(blank=True, default='https://thenounproject.com/icon/default-image-4595376/', null=True, upload_to='item_images'),
        ),
        migrations.AddField(
            model_name='item',
            name='image_3',
            field=models.ImageField(blank=True, default='https://thenounproject.com/icon/default-image-4595376/', null=True, upload_to='item_images'),
        ),
        migrations.AddField(
            model_name='item',
            name='image_4',
            field=models.ImageField(blank=True, default='https://thenounproject.com/icon/default-image-4595376/', null=True, upload_to='item_images'),
        ),
    ]
