# Generated by Django 4.2.1 on 2024-01-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_item_image_2_item_image_3_item_image_4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image_2',
            field=models.ImageField(blank=True, default='https://bestimp.ro/global/images/default-image.png', null=True, upload_to='item_images'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_3',
            field=models.ImageField(blank=True, default='https://bestimp.ro/global/images/default-image.png', null=True, upload_to='item_images'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_4',
            field=models.ImageField(blank=True, default='https://bestimp.ro/global/images/default-image.png', null=True, upload_to='item_images'),
        ),
    ]
