# Generated by Django 4.2.1 on 2024-01-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_alter_item_image_2_alter_item_image_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='locatie',
            field=models.CharField(default='Locatie nespecificata', max_length=100),
        ),
    ]
