# Generated by Django 4.2.1 on 2024-01-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_item_locatie'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='item_images/default-image.png', null=True, upload_to='category_images'),
        ),
    ]
