# Generated by Django 4.2.1 on 2024-01-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='access_count',
            field=models.IntegerField(default=0),
        ),
    ]
